yarnPath: .yarn/releases/yarn-4.9.2.cjs
pnpEnableEsmLoader: true
nmHoistingLimits: workspaces

# i dont want "works in my machine" or any other stuff
# this makes the @ssword/ui package use the same packages as my
# site

nodeLinker: pnp
enableGlobalCache: true
